// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api/players.ts";
import * as $2 from "./routes/api/server.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/map.tsx";
import * as $5 from "./routes/players.tsx";
import * as $$0 from "./islands/PlayersInfo.tsx";
import * as $$1 from "./islands/ServerInfo.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/players.ts": $1,
    "./routes/api/server.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/map.tsx": $4,
    "./routes/players.tsx": $5,
  },
  islands: {
    "./islands/PlayersInfo.tsx": $$0,
    "./islands/ServerInfo.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
